# Generated by Django 5.1.1 on 2024-10-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='images/')),
                ('text', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField()),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('stock', models.PositiveIntegerField()),
                ('manufacturer', models.TextField()),
            ],
        ),
    ]
